version: '3.9'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
      - "5005:5005"
      - "5055:5055"
      - "11434:11434"  # Ollama port
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production