services:
  - type: web
    name: mental-health-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000